version: '3'
services:
  redis:
    image: docker.io/bitnami/redis:7.0
    container_name: redis
    networks:
      - backend
    environment:
      - REDIS_PASSWORD=<PASSWORD>
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - '/volume1/configs/redis:/bitnami/redis/data'

networks:
  backend:
